name: qzx-mac-beta
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run VNC + ngrok setup
        run: |
          chmod +x start.sh
          ./start.sh "$NGROK_AUTH_TOKEN"

      - name: Show ngrok tunnel URL
        run: |
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels
